# Generated by Django 2.2 on 2020-03-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoChiper',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=25)),
            ],
        ),
    ]
