# Generated by Django 2.2 on 2020-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
