# Generated by Django 2.2 on 2020-03-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoPedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productopedido',
            table='PRODUCTOPEDIDO',
        ),
    ]
