# Generated by Django 3.0.4 on 2020-03-24 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoChiper', '0001_initial'),
        ('productoVenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='producto',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='productoChiper.ProductoChiper'),
        ),
    ]
