# Generated by Django 2.2 on 2020-03-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendero',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=200)),
                ('edad', models.PositiveSmallIntegerField()),
                ('celular', models.CharField(max_length=80)),
                ('RUT', models.BigIntegerField()),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda')),
            ],
        ),
    ]
