# Generated by Django 2.2 on 2020-03-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoChiper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productochiper',
            table='PRODUCTOCHIPER',
        ),
    ]
