# Generated by Django 2.2 on 2020-03-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoVenta', '0002_productoventa_producto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoventa',
            table='PRODUCTOVENTA',
        ),
    ]
