# Generated by Django 2.2 on 2020-03-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoVenta', '0003_auto_20200326_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoChiper.ProductoChiper'),
        ),
    ]
