# Generated by Django 3.0.4 on 2020-03-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productoChiper', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=80)),
                ('limiteProd', models.IntegerField()),
                ('productos', models.ManyToManyField(to='productoChiper.ProductoChiper')),
                ('zona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='zonas.Zona')),
            ],
        ),
    ]
