# Generated by Django 3.0.4 on 2020-03-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='limiteProd',
        ),
    ]
