insert into zonas_zona (id, nombre, descripcion) values ('1', 'Rogahn, Lowe and King', 'Nondisp fx of trapezoid, left wrist, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('2', 'Dare, Runolfsdottir and O''Hara', 'Complete traumatic amputation of one unsp lesser toe, subs');
insert into zonas_zona (id, nombre, descripcion) values ('3', 'Brown, Kunde and Rogahn', 'Cardiovascular syphilis, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('4', 'Wiegand, Kub and Hermiston', 'Other diphtheria');
insert into zonas_zona (id, nombre, descripcion) values ('5', 'Ritchie-Walker', 'Unspecified superficial injury of forearm');
insert into zonas_zona (id, nombre, descripcion) values ('6', 'Cummings, Wiza and McGlynn', 'Drug-induced chronic gout, unspecified knee, without tophus');
insert into zonas_zona (id, nombre, descripcion) values ('7', 'Gusikowski-Mayert', 'Toxic effect of detergents, intentional self-harm');
insert into zonas_zona (id, nombre, descripcion) values ('8', 'Cormier Group', 'Intcran inj w LOC >24 hr w/o ret consc w surv, subs');
insert into zonas_zona (id, nombre, descripcion) values ('9', 'Watsica and Sons', 'Unsp traum nondisp spondylolysis of sixth cervcal vert, init');
insert into zonas_zona (id, nombre, descripcion) values ('10', 'Bernier, Hayes and Wehner', 'Nondisp fx of lateral malleolus of r fibula, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('11', 'Reichert Group', 'Toxic effect of unsp metal, accidental (unintentional), subs');
insert into zonas_zona (id, nombre, descripcion) values ('12', 'Feeney-Beer', 'Contusion of left foot, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('13', 'Rogahn-Hoppe', 'Infect/inflm reaction due to int fix of r fibula, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('14', 'Bernhard-Koelpin', 'Burn of unspecified degree of neck, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('15', 'Stokes-Lowe', 'Pnctr of abd wall w fb, r upper q w/o penet perit cav, subs');
insert into zonas_zona (id, nombre, descripcion) values ('16', 'Rippin, Veum and McGlynn', 'Bitten by duck, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('17', 'Connelly-Lockman', 'Struck by dog, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('18', 'Cassin-DuBuque', 'Nondisp comminuted fx shaft of ulna, right arm, init');
insert into zonas_zona (id, nombre, descripcion) values ('19', 'Turcotte Group', 'Spontaneous rupture of other tendons, lower leg');
insert into zonas_zona (id, nombre, descripcion) values ('20', 'Kessler LLC', 'Nondisp fx of lateral condyle of l tibia, 7thP');
insert into zonas_zona (id, nombre, descripcion) values ('21', 'Skiles, Christiansen and Heller', 'Cont pregnancy after spon abortion of one fetus or more');
insert into zonas_zona (id, nombre, descripcion) values ('22', 'Kilback-Hills', 'Other enthesopathy of unspecified foot');
insert into zonas_zona (id, nombre, descripcion) values ('23', 'Yundt-Brekke', 'Pnctr w fb of left lesser toe(s) w damage to nail, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('24', 'Hyatt, Stokes and Upton', 'Injury due to collapse of burning bldg in ctrl fire, subs');
insert into zonas_zona (id, nombre, descripcion) values ('25', 'McCullough Group', 'Laceration without foreign body of unsp buttock, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('26', 'Emard, Gleichner and Mertz', 'Poisoning by MAO inhib antidepressants, self-harm, subs');
insert into zonas_zona (id, nombre, descripcion) values ('27', 'Littel Inc', 'Poisoning by unsp drugs acting on muscles, assault, subs');
insert into zonas_zona (id, nombre, descripcion) values ('28', 'McDermott, Smith and Kilback', 'Ankylosis, left hip');
insert into zonas_zona (id, nombre, descripcion) values ('29', 'Auer-Schinner', 'Disp fx of proximal phalanx of unspecified lesser toe(s)');
insert into zonas_zona (id, nombre, descripcion) values ('30', 'Hilpert LLC', 'Malignant melanoma of other part of trunk');
insert into zonas_zona (id, nombre, descripcion) values ('31', 'Koss Group', 'Corrosion of first degree of unspecified forearm');
insert into zonas_zona (id, nombre, descripcion) values ('32', 'Altenwerth, Hackett and Bradtke', 'Enophthalmos due to atrophy of orbital tissue, bilateral');
insert into zonas_zona (id, nombre, descripcion) values ('33', 'Upton-Schiller', 'Dermatochalasis of left upper eyelid');
insert into zonas_zona (id, nombre, descripcion) values ('34', 'Howell and Sons', 'Type III occipital condyle fracture, unspecified side, 7thK');
insert into zonas_zona (id, nombre, descripcion) values ('35', 'Nicolas Inc', 'Mechanical complication of bone devices, implants and grafts');
insert into zonas_zona (id, nombre, descripcion) values ('36', 'Mann, Hagenes and Shanahan', 'Oth injury of intercostal blood vessels, unspecified side');
insert into zonas_zona (id, nombre, descripcion) values ('37', 'Champlin, Bartoletti and Flatley', 'Post-traumatic osteoarthritis, right wrist');
insert into zonas_zona (id, nombre, descripcion) values ('38', 'Heaney-Corkery', 'Infect/inflm react d/t oth cardi/vasc dev/implnt/grft, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('39', 'Wintheiser-Senger', 'Nondisp fx of med condyle of r femr, 7thE');
insert into zonas_zona (id, nombre, descripcion) values ('40', 'Johns and Sons', 'Sprain of left acromioclavicular joint, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('41', 'Hilpert-Lang', 'Toxic effect of trichloroethylene, accidental, subs');
insert into zonas_zona (id, nombre, descripcion) values ('42', 'Rutherford-Predovic', 'Other secondary chronic gout, right knee, with tophus');
insert into zonas_zona (id, nombre, descripcion) values ('43', 'Pollich Inc', 'Pre-existing secondary htn comp pregnancy, first trimester');
insert into zonas_zona (id, nombre, descripcion) values ('44', 'Ortiz, Brown and Price', 'Other meniscus derangements, unsp medial meniscus, unsp knee');
insert into zonas_zona (id, nombre, descripcion) values ('45', 'Bauch Inc', 'Other  specified congenital deformities of feet');
insert into zonas_zona (id, nombre, descripcion) values ('46', 'Deckow-McKenzie', 'Toxic effect of venom of African and Asian snake, assault');
insert into zonas_zona (id, nombre, descripcion) values ('47', 'Reynolds LLC', 'Ankylosis of ear ossicles, bilateral');
insert into zonas_zona (id, nombre, descripcion) values ('48', 'Rolfson LLC', 'Poisoning by unsp topical agent, self-harm, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('49', 'Hickle-Kub', 'Nondisp transverse fx shaft of l fibula, 7thH');
insert into zonas_zona (id, nombre, descripcion) values ('50', 'Kutch, Weimann and Champlin', 'Disorder of kidney and ureter, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('51', 'Hettinger, Kshlerin and Brown', 'Partial loss of teeth due to periodontal diseases, class I');
insert into zonas_zona (id, nombre, descripcion) values ('52', 'Schaden, Hagenes and Von', 'Laceration without foreign body of lip, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('53', 'Lowe, Wiegand and Pouros', 'Nondisplaced oblique fracture of shaft of unsp ulna, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('54', 'Pfannerstill, Terry and Douglas', 'Acute coronary thrombosis not resulting in myocardial infrc');
insert into zonas_zona (id, nombre, descripcion) values ('55', 'Wintheiser LLC', 'Pnctr w foreign body of unsp finger w damage to nail');
insert into zonas_zona (id, nombre, descripcion) values ('56', 'Mosciski LLC', 'Toxic effect of venom of other African and Asian snake');
insert into zonas_zona (id, nombre, descripcion) values ('57', 'Strosin-Lubowitz', 'Unsp inj musc/tend ant grp at low leg level, right leg, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('58', 'Becker LLC', 'Nondisp transverse fx shaft of l fibula, 7thC');
insert into zonas_zona (id, nombre, descripcion) values ('59', 'Conroy Inc', 'Contusion of fallopian tube, unilateral, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('60', 'Gutkowski-Yundt', 'NIHSS score 21');
insert into zonas_zona (id, nombre, descripcion) values ('61', 'Haley, Haley and Upton', 'Daycare center childcare prov, perp of maltreat and neglect');
insert into zonas_zona (id, nombre, descripcion) values ('62', 'Heaney, Bartell and Smitham', 'Burn first degree of unsp mult fngr, not inc thumb, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('63', 'Rath Inc', 'Laceration of bladder, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('64', 'Armstrong-Wehner', 'Poisoning by benzodiazepines, assault');
insert into zonas_zona (id, nombre, descripcion) values ('65', 'Pouros-McKenzie', 'Disp fx of lateral condyle of unsp tibia, 7thJ');
insert into zonas_zona (id, nombre, descripcion) values ('66', 'Altenwerth, Ratke and Balistreri', 'Fall into swimming pool striking surfc causing drown, subs');
insert into zonas_zona (id, nombre, descripcion) values ('67', 'Green-Walker', 'Greenstick fx shaft of right ulna, subs for fx w delay heal');
insert into zonas_zona (id, nombre, descripcion) values ('68', 'Nitzsche, Doyle and Brekke', 'Crushing injury of left elbow, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('69', 'Glover, Koepp and Berge', 'Unspecified superficial injury of right elbow, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('70', 'Deckow-Bartoletti', 'Disp fx of neck of left rad, subs for clos fx w routn heal');
insert into zonas_zona (id, nombre, descripcion) values ('71', 'Kris, Huels and Klein', 'Other water transport accident, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('72', 'O''Reilly, Hirthe and Durgan', 'Other specified injury of blood vessel of left ring finger');
insert into zonas_zona (id, nombre, descripcion) values ('73', 'Upton, Kuhn and Osinski', 'Nondisp transverse fx shaft of l tibia, 7thQ');
insert into zonas_zona (id, nombre, descripcion) values ('74', 'Langworth, Schimmel and Feest', 'Oth injuries of unsp wrist, hand and finger(s), sequela');
insert into zonas_zona (id, nombre, descripcion) values ('75', 'Dare, Graham and Lang', 'Lacerat musc/tend at lower leg level, right leg, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('76', 'Labadie Group', 'Juvenile osteochondrosis of tibia and fibula, right leg');
insert into zonas_zona (id, nombre, descripcion) values ('77', 'Breitenberg and Sons', 'Nondisp fx of greater trochanter of l femr, 7thR');
insert into zonas_zona (id, nombre, descripcion) values ('78', 'Stamm-Grimes', 'Unsp pedl cyclst inj in clsn w nonmtr vehicle in traf, init');
insert into zonas_zona (id, nombre, descripcion) values ('79', 'Homenick Inc', 'Milt op involving oth explosn and fragmt, civilian, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('80', 'Williamson Inc', 'Nondisp fx of lateral condyle of left humerus, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('81', 'Barrows Group', 'Cystoid macular degeneration, left eye');
insert into zonas_zona (id, nombre, descripcion) values ('82', 'Hills-Jones', 'Mild persistent asthma, uncomplicated');
insert into zonas_zona (id, nombre, descripcion) values ('83', 'Hudson, Jerde and Strosin', 'Ant disp fx of sternal end of r clavicle, init for opn fx');
insert into zonas_zona (id, nombre, descripcion) values ('84', 'West-Larkin', 'Other chondrocalcinosis, left shoulder');
insert into zonas_zona (id, nombre, descripcion) values ('85', 'Stracke-Huels', 'Oth and unspecified types of non-Hodgkin lymphoma');
insert into zonas_zona (id, nombre, descripcion) values ('86', 'Crona, Kling and Jenkins', 'Pedl cyc driver injured in clsn w ped/anml nontraf, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('87', 'Zieme-Lindgren', 'Fracture of subcondylar process of left mandible');
insert into zonas_zona (id, nombre, descripcion) values ('88', 'Mitchell and Sons', 'Posterior dislocation of unspecified humerus, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('89', 'Koepp, Langworth and Kirlin', 'Other sprain of right ring finger');
insert into zonas_zona (id, nombre, descripcion) values ('90', 'Prosacco Inc', 'Partial traumatic metacarpophalangeal amputation of thmb');
insert into zonas_zona (id, nombre, descripcion) values ('91', 'Brown-Bins', 'Laceration of superficial palmar arch of unsp hand, init');
insert into zonas_zona (id, nombre, descripcion) values ('92', 'Grimes LLC', 'Vasomotor rhinitis');
insert into zonas_zona (id, nombre, descripcion) values ('93', 'Wiegand, Satterfield and Greenfelder', 'Unspecified mononeuropathy of lower limb');
insert into zonas_zona (id, nombre, descripcion) values ('94', 'Hane and Sons', 'Degenerative disease of nervous system, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('95', 'Champlin, O''Kon and Grady', 'Poisoning by intravenous anesthetics, assault, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('96', 'Eichmann and Sons', 'Inj extn musc/fasc/tend at forearm level, right arm, init');
insert into zonas_zona (id, nombre, descripcion) values ('97', 'Volkman-Reinger', 'Fall (on)(from) incline, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('98', 'Rempel-Parisian', 'Partial physeal arrest, right distal tibia');
insert into zonas_zona (id, nombre, descripcion) values ('99', 'Blick-Runolfsdottir', 'Laceration with foreign body of right ear, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('100', 'Goyette Inc', 'Abrasion of breast');
insert into zonas_zona (id, nombre, descripcion) values ('101', 'Wunsch Group', 'Corrosion of unsp deg mult fingers (nail), including thumb');
insert into zonas_zona (id, nombre, descripcion) values ('102', 'Kertzmann, Larson and Braun', 'Enteropathic arthropathies, right ankle and foot');
insert into zonas_zona (id, nombre, descripcion) values ('103', 'DuBuque LLC', 'Contusion of unspecified external genital organ, female');
insert into zonas_zona (id, nombre, descripcion) values ('104', 'Heaney-Kutch', 'Recurrent subluxation of patella, unspecified knee');
insert into zonas_zona (id, nombre, descripcion) values ('105', 'Jenkins, Greenholt and Walter', 'Poisoning by other psychotropic drugs, undetermined');
insert into zonas_zona (id, nombre, descripcion) values ('106', 'Tillman, Feest and Kessler', 'Newborn light for gestational age, 500-749 grams');
insert into zonas_zona (id, nombre, descripcion) values ('107', 'Mann-Bauch', 'Nondisp fx of base of nk of r femr, 7thG');
insert into zonas_zona (id, nombre, descripcion) values ('108', 'Hammes LLC', 'Unsp acc to oth private fix-wing aircraft, injuring occupant');
insert into zonas_zona (id, nombre, descripcion) values ('109', 'Quitzon, Gulgowski and Walsh', 'Unspecified astigmatism, left eye');
insert into zonas_zona (id, nombre, descripcion) values ('110', 'Sipes-Schmeler', 'Oth physl fx upr end humer, left arm, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('111', 'Howe, Jacobs and Jones', 'Military operations involving friendly fire');
insert into zonas_zona (id, nombre, descripcion) values ('112', 'Hansen, Torphy and Hyatt', 'Hepatomegaly and splenomegaly, not elsewhere classified');
insert into zonas_zona (id, nombre, descripcion) values ('113', 'Kuhn-Yundt', 'Diffus folicl cntr lymph, nodes of ing region and lower limb');
insert into zonas_zona (id, nombre, descripcion) values ('114', 'Heidenreich, Little and Farrell', 'Palpitations');
insert into zonas_zona (id, nombre, descripcion) values ('115', 'Keeling-Swift', 'Acute myringitis, left ear');
insert into zonas_zona (id, nombre, descripcion) values ('116', 'Rippin, Huel and Wiegand', 'Unsp injury of extn/abdr musc/fasc/tend of thmb at forarm lv');
insert into zonas_zona (id, nombre, descripcion) values ('117', 'Connelly and Sons', 'Unsp injury of right internal jugular vein, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('118', 'Cartwright and Sons', 'Premature separation of placenta w dissem intravasc coag');
insert into zonas_zona (id, nombre, descripcion) values ('119', 'Kuhlman Inc', 'Tay-Sachs disease');
insert into zonas_zona (id, nombre, descripcion) values ('120', 'Hickle, Wintheiser and Cummings', 'Superficial foreign body of abdominal wall');
insert into zonas_zona (id, nombre, descripcion) values ('121', 'Flatley-Eichmann', 'Cerebral infarction due to embolism of basilar artery');
insert into zonas_zona (id, nombre, descripcion) values ('122', 'Stokes Group', 'External constriction, right lesser toe(s), subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('123', 'Kessler, Berge and Bode', 'Encounter for care and examination of lactating mother');
insert into zonas_zona (id, nombre, descripcion) values ('124', 'Zieme, Yost and Aufderhar', 'Nondisp fx of cuboid bone of r ft, subs for fx w routn heal');
insert into zonas_zona (id, nombre, descripcion) values ('125', 'Kuhn-Gottlieb', 'Coma scale, best verb, inappropriate words, 24+hrs');
insert into zonas_zona (id, nombre, descripcion) values ('126', 'Schuster Inc', 'Unspecified injury of neck');
insert into zonas_zona (id, nombre, descripcion) values ('127', 'O''Kon LLC', 'Path fx in neopltc dis, hip, unsp, subs for fx w delay heal');
insert into zonas_zona (id, nombre, descripcion) values ('128', 'Bradtke, Wyman and Upton', 'Unilateral inguinal hernia, without obstruction or gangrene');
insert into zonas_zona (id, nombre, descripcion) values ('129', 'Corwin-Cummings', 'Sltr-haris Type IV physl fx low end humer, l arm, 7thG');
insert into zonas_zona (id, nombre, descripcion) values ('130', 'Feil-Goyette', 'Stiffness of left ankle, not elsewhere classified');
insert into zonas_zona (id, nombre, descripcion) values ('131', 'Champlin-Konopelski', 'Major anomalies of jaw size');
insert into zonas_zona (id, nombre, descripcion) values ('132', 'Pacocha Group', 'Oth comp of fb acc left in body fol injection or immuniz');
insert into zonas_zona (id, nombre, descripcion) values ('133', 'Hegmann and Sons', 'Driver injured in collision w oth mv nontraf, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('134', 'D''Amore Group', 'Abrasion of vagina and vulva, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('135', 'Buckridge-Okuneva', 'Cervical rib');
insert into zonas_zona (id, nombre, descripcion) values ('136', 'Sanford Inc', 'Bitten by dog, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('137', 'Lesch-Berge', 'Laceration of axillary artery, left side, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('138', 'Heaney and Sons', 'Recurrent pregnancy loss');
insert into zonas_zona (id, nombre, descripcion) values ('139', 'Torp, Kiehn and Fadel', 'Unspecified congenital malformation of bladder and urethra');
insert into zonas_zona (id, nombre, descripcion) values ('140', 'Bailey LLC', 'Dissection of artery of upper extremity');
insert into zonas_zona (id, nombre, descripcion) values ('141', 'Buckridge and Sons', 'Blepharochalasis left upper eyelid');
insert into zonas_zona (id, nombre, descripcion) values ('142', 'McKenzie, Hodkiewicz and Pouros', 'Unsp injury of less saphenous at lower leg level, unsp leg');
insert into zonas_zona (id, nombre, descripcion) values ('143', 'Runolfsdottir LLC', 'Displaced intraarticular fracture of right calcaneus, init');
insert into zonas_zona (id, nombre, descripcion) values ('144', 'Pagac and Sons', 'Unsp hang-glider accident injuring occupant, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('145', 'Stehr Inc', 'Thyroiditis, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('146', 'Lesch-Leuschke', 'Chronic gout due to renal impairment, unsp elbow, w/o tophus');
insert into zonas_zona (id, nombre, descripcion) values ('147', 'Harvey and Sons', 'Traumatic hemopneumothorax, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('148', 'Bashirian-Rice', 'Nondisp fx of greater tuberosity of unsp humer, 7thG');
insert into zonas_zona (id, nombre, descripcion) values ('149', 'Rutherford-Mitchell', 'Contusion of right back wall of thorax, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('150', 'Daniel-Mosciski', 'Unsp inj unsp blood vess at ank/ft level, left leg, init');
insert into zonas_zona (id, nombre, descripcion) values ('151', 'Price-Tillman', 'Circadian rhythm sleep disorder, delayed sleep phase type');
insert into zonas_zona (id, nombre, descripcion) values ('152', 'Johns and Sons', 'Complications of stoma of urinary tract');
insert into zonas_zona (id, nombre, descripcion) values ('153', 'Ebert Group', 'Displ artic fx head of l femr, 7thN');
insert into zonas_zona (id, nombre, descripcion) values ('154', 'Zulauf Inc', 'Disp fx of r radial styloid pro, 7thF');
insert into zonas_zona (id, nombre, descripcion) values ('155', 'Bernhard, Daugherty and Tremblay', 'Strain intrns musc/fasc/tend l idx fngr at wrs/hnd lv, init');
insert into zonas_zona (id, nombre, descripcion) values ('156', 'Hayes-Ledner', 'Rheumatoid nodule, unspecified ankle and foot');
insert into zonas_zona (id, nombre, descripcion) values ('157', 'Lehner Group', 'Disp fx of olecran pro w intartic extn left ulna, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('158', 'Gleichner, Crona and Larkin', 'Jump/div into oth water strk bottom causing oth injury, subs');
insert into zonas_zona (id, nombre, descripcion) values ('159', 'McClure and Sons', 'Disp fx of med epicondyl of unsp humer, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('160', 'McClure, Hamill and Jacobi', 'Maternal care for excess fetal growth, first tri, fetus 4');
insert into zonas_zona (id, nombre, descripcion) values ('161', 'Jones, Fisher and Moore', 'Corrosion of second degree of unspecified forearm, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('162', 'Wisoky-Hand', 'Corrosion of first degree of forehead and cheek, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('163', 'Homenick-Wuckert', 'Oth acute nonsuppurative otitis media, recurrent, bilateral');
insert into zonas_zona (id, nombre, descripcion) values ('164', 'Skiles, Hauck and Bartoletti', 'Pauciarticular juvenile rheumatoid arthritis, left ank/ft');
insert into zonas_zona (id, nombre, descripcion) values ('165', 'Runolfsson-Kuhic', 'Inj flexor musc/fasc/tend finger at wrist and hand level');
insert into zonas_zona (id, nombre, descripcion) values ('166', 'Cormier, Goldner and Stracke', 'Contusion of foot');
insert into zonas_zona (id, nombre, descripcion) values ('167', 'Schuster, Wintheiser and Zulauf', 'Histoplasmosis');
insert into zonas_zona (id, nombre, descripcion) values ('168', 'Lebsack-Renner', 'Displ commnt fx shaft of r tibia, 7thR');
insert into zonas_zona (id, nombre, descripcion) values ('169', 'Hane-Bergstrom', 'Commrcl fix-wing aircraft collision injuring occupant, subs');
insert into zonas_zona (id, nombre, descripcion) values ('170', 'Treutel, Daugherty and Koch', 'Latent nystagmus');
insert into zonas_zona (id, nombre, descripcion) values ('171', 'Sawayn Inc', 'Injury of optic chiasm');
insert into zonas_zona (id, nombre, descripcion) values ('172', 'Nader-Mayert', 'Gonococcal arthritis');
insert into zonas_zona (id, nombre, descripcion) values ('173', 'McKenzie Group', 'Advrs effect of unsp nonopi analgs/antipyr/antirheu, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('174', 'West-Dicki', 'Other and unspecified dorsopathies, not elsewhere classified');
insert into zonas_zona (id, nombre, descripcion) values ('175', 'Muller, Frami and Hartmann', 'Degenerative myopia, bilateral');
insert into zonas_zona (id, nombre, descripcion) values ('176', 'Nolan Group', 'Lacerat intrns musc/fasc/tend finger at wrs/hnd lv, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('177', 'Sanford-Erdman', 'Flatback syndrome, site unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('178', 'Wolff, Jacobi and Sanford', 'Exudative cysts of iris or anterior chamber, unspecified eye');
insert into zonas_zona (id, nombre, descripcion) values ('179', 'Franecki-Swaniawski', 'Prsn brd/alit pedl cyc inj in clsn w nonmtr veh nontraf,sqla');
insert into zonas_zona (id, nombre, descripcion) values ('180', 'Walker and Sons', 'Disp fx of neck of second metacarpal bone, right hand, init');
insert into zonas_zona (id, nombre, descripcion) values ('181', 'Zboncak, Padberg and Bailey', 'Insect bite (nonvenomous) of unspecified finger');
insert into zonas_zona (id, nombre, descripcion) values ('182', 'Hilpert Inc', 'Oth nondisp fx of base of 1st MC bone, unsp hand, 7thP');
insert into zonas_zona (id, nombre, descripcion) values ('183', 'Deckow, Renner and Beatty', 'Chalazion left eye, unspecified eyelid');
insert into zonas_zona (id, nombre, descripcion) values ('184', 'Konopelski Group', 'Preglaucoma, unspecified, unspecified eye');
insert into zonas_zona (id, nombre, descripcion) values ('185', 'Kilback, Crona and McDermott', 'Chronic myringitis, right ear');
insert into zonas_zona (id, nombre, descripcion) values ('186', 'Rodriguez, Durgan and Mitchell', 'Unspecified otitis externa');
insert into zonas_zona (id, nombre, descripcion) values ('187', 'Runte, Robel and Considine', 'Monocular esotropia, left eye');
insert into zonas_zona (id, nombre, descripcion) values ('188', 'Fahey-Nader', 'Unspecified superficial injury of left ear, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('189', 'Runte, Morissette and Brown', 'Injury of peripheral nerves of neck');
insert into zonas_zona (id, nombre, descripcion) values ('190', 'Cole, Homenick and Spinka', 'Injury of other nerves at lower leg level, unsp leg, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('191', 'Larkin Inc', 'Prsn outsd 3-whl mv inj pk-up truck, pk-up/van nontraf, subs');
insert into zonas_zona (id, nombre, descripcion) values ('192', 'Ritchie Group', 'Ambulatory surgery center as place');
insert into zonas_zona (id, nombre, descripcion) values ('193', 'Upton Inc', 'Displ suprcndl fx w/o intrcndl extn low end unsp femr, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('194', 'Marvin-Schimmel', 'Unsp injury of right wrist, hand and finger(s), subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('195', 'Labadie-Steuber', 'Fall into swimming pool strk bottom causing drown, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('196', 'Waelchi-Labadie', 'Struck by other hit or thrown ball, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('197', 'Bernhard-Orn', 'Malignant neoplasm of overlapping sites of stomach');
insert into zonas_zona (id, nombre, descripcion) values ('198', 'Blanda, Goldner and Skiles', 'Type 1 diabetes mellitus with circulatory complications');
insert into zonas_zona (id, nombre, descripcion) values ('199', 'Hintz-Hirthe', 'Injury of other iliac blood vessels, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('200', 'Hahn-Haley', 'Disp fx of med condyle of unsp femr, 7thF');
insert into zonas_zona (id, nombre, descripcion) values ('201', 'Gleichner-Goyette', 'Laceration of left renal artery, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('202', 'Rohan LLC', 'Struck by falling object on passenger ship, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('203', 'Armstrong-Osinski', 'Corros first deg mult sites of unsp lower limb, ex ank/ft');
insert into zonas_zona (id, nombre, descripcion) values ('204', 'Batz, Tremblay and Davis', 'Other streptococcal arthritis, unspecified hand');
insert into zonas_zona (id, nombre, descripcion) values ('205', 'Erdman-Gerhold', 'External constriction of right middle finger');
insert into zonas_zona (id, nombre, descripcion) values ('206', 'Connelly and Sons', 'Lac w/o fb of abd wall, periumb rgn w penet perit cav, subs');
insert into zonas_zona (id, nombre, descripcion) values ('207', 'Walsh Group', 'Disp fx of unsp radial styloid pro, 7thN');
insert into zonas_zona (id, nombre, descripcion) values ('208', 'Stokes, Jakubowski and Wehner', 'Degenerative disease of basal ganglia, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('209', 'Aufderhar Group', 'Unspecified open wound of right shoulder, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('210', 'Langosh-Hyatt', 'Toxic effect of cntct w Portugese Man-o-war, asslt, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('211', 'Konopelski, Paucek and Kreiger', 'Strain of unspecified Achilles tendon');
insert into zonas_zona (id, nombre, descripcion) values ('212', 'Konopelski, Lowe and Reilly', 'Other interstitial and deep keratitis, right eye');
insert into zonas_zona (id, nombre, descripcion) values ('213', 'McLaughlin, Wiegand and Nikolaus', 'Other injury of rectum, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('214', 'Ondricka LLC', 'Fractured dental restorative material with loss of material');
insert into zonas_zona (id, nombre, descripcion) values ('215', 'Ernser-Keebler', 'Anterior cord syndrome at C8, subs');
insert into zonas_zona (id, nombre, descripcion) values ('216', 'Shields Inc', 'Disp fx of cuboid bone of unsp ft, subs for fx w delay heal');
insert into zonas_zona (id, nombre, descripcion) values ('217', 'Hauck, Gleichner and Schinner', 'Pinta [carate]');
insert into zonas_zona (id, nombre, descripcion) values ('218', 'Breitenberg LLC', 'Unspecified physeal fracture of upper end of femur');
insert into zonas_zona (id, nombre, descripcion) values ('219', 'Barton-Wiza', 'Nondisplaced fracture of trapezium, right wrist, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('220', 'Funk, Runolfsson and Kozey', 'Inj flexor musc/fasc/tend l mid finger at forearm level');
insert into zonas_zona (id, nombre, descripcion) values ('221', 'Strosin and Sons', 'Oth fx shaft of l tibia, 7thR');
insert into zonas_zona (id, nombre, descripcion) values ('222', 'Bergstrom-Grimes', 'Complete lesion of L2 level of lumbar spinal cord, subs');
insert into zonas_zona (id, nombre, descripcion) values ('223', 'Beier-Morissette', 'Chronic embolism and thrombosis of other thoracic veins');
insert into zonas_zona (id, nombre, descripcion) values ('224', 'Gleichner Group', 'Nondisplaced Rolando''s fracture, right hand');
insert into zonas_zona (id, nombre, descripcion) values ('225', 'Prohaska, Denesik and Powlowski', 'Lacerat intrinsic musc/fasc/tend r rng fngr at wrs/hnd lv');
insert into zonas_zona (id, nombre, descripcion) values ('226', 'King, Balistreri and Ortiz', 'Occup of pk-up/van inj in clsn w nonmtr veh in traf, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('227', 'Veum-Fisher', 'Ring corneal ulcer, unspecified eye');
insert into zonas_zona (id, nombre, descripcion) values ('228', 'Sauer, Langworth and Rogahn', 'Drown while in bathtub, undetermined intent, init');
insert into zonas_zona (id, nombre, descripcion) values ('229', 'Mills, Moen and Mante', 'Coma scale, eyes open, to sound, at hospital admission');
insert into zonas_zona (id, nombre, descripcion) values ('230', 'Steuber, Prohaska and Effertz', 'Toxic liver disease with acute hepatitis');
insert into zonas_zona (id, nombre, descripcion) values ('231', 'Kautzer Group', 'Open bite, right thigh');
insert into zonas_zona (id, nombre, descripcion) values ('232', 'Tremblay, Flatley and Vandervort', 'Unspecified subluxation and dislocation of patella');
insert into zonas_zona (id, nombre, descripcion) values ('233', 'Nader LLC', 'Primary blast injury oth prt small intestine, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('234', 'Emard-Bednar', 'Other cerebral infarction');
insert into zonas_zona (id, nombre, descripcion) values ('235', 'Abbott Group', 'Chronic osteomyelitis with draining sinus, right hand');
insert into zonas_zona (id, nombre, descripcion) values ('236', 'Schimmel Group', 'Other fracture of second metacarpal bone, right hand');
insert into zonas_zona (id, nombre, descripcion) values ('237', 'Wehner, Dooley and Walsh', 'Disp fx of prox phalanx of thmb, subs for fx w routn heal');
insert into zonas_zona (id, nombre, descripcion) values ('238', 'Hirthe, Lang and Heathcote', 'Sltr-haris Type III physeal fx phalanx of right toe, 7thP');
insert into zonas_zona (id, nombre, descripcion) values ('239', 'Dach, DuBuque and Bogisich', 'Pigmentary glaucoma, bilateral, moderate stage');
insert into zonas_zona (id, nombre, descripcion) values ('240', 'McGlynn, White and Collins', 'Cataract secondary to ocular disorders, unsp eye');
insert into zonas_zona (id, nombre, descripcion) values ('241', 'West Group', 'Nondisp fx of lateral epicondyl of r humer, init for opn fx');
insert into zonas_zona (id, nombre, descripcion) values ('242', 'Hackett, Rowe and Murazik', 'Nondisp commnt fx r patella, subs for clos fx w delay heal');
insert into zonas_zona (id, nombre, descripcion) values ('243', 'Hoeger, Muller and Frami', 'Supervision of pregnancy with history of pre-term labor');
insert into zonas_zona (id, nombre, descripcion) values ('244', 'Dare, Thompson and Champlin', 'Drown d/t being washed ovrbrd from oth power wtrcrft, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('245', 'Boehm-Fadel', 'Person outside bus injured in clsn w nonmtr vehicle nontraf');
insert into zonas_zona (id, nombre, descripcion) values ('246', 'Tremblay and Sons', 'Traum hemor right cerebrum w LOC of 31-59 min, subs');
insert into zonas_zona (id, nombre, descripcion) values ('247', 'Yundt LLC', 'Major contusion of right kidney, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('248', 'Metz Inc', 'Postproc hematoma of a circ sys org fol a circ sys procedure');
insert into zonas_zona (id, nombre, descripcion) values ('249', 'McLaughlin Group', 'Nondisp fx of neck of scapula, l shoulder, init for opn fx');
insert into zonas_zona (id, nombre, descripcion) values ('250', 'West Group', 'Laceration w fb of r little finger w damage to nail');
insert into zonas_zona (id, nombre, descripcion) values ('251', 'Stokes Inc', 'Adverse effect of other narcotics');
insert into zonas_zona (id, nombre, descripcion) values ('252', 'Hills-Stroman', 'Driver of pk-up/van inj in clsn w oth and unsp mv nontraf');
insert into zonas_zona (id, nombre, descripcion) values ('253', 'Braun, Kreiger and Kertzmann', 'Other non-follicular lymphoma, spleen');
insert into zonas_zona (id, nombre, descripcion) values ('254', 'Beer, Sporer and Ortiz', 'Disp fx of less trochanter of unsp femr, 7thH');
insert into zonas_zona (id, nombre, descripcion) values ('255', 'Jenkins-Champlin', 'Person outsd car inj in clsn w statnry object nontraf, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('256', 'Reichel Group', 'Disp fx of shaft of unsp clavicle, subs for fx w delay heal');
insert into zonas_zona (id, nombre, descripcion) values ('257', 'Nitzsche and Sons', 'Person outside hv veh inj in clsn w 2/3-whl mv nontraf, init');
insert into zonas_zona (id, nombre, descripcion) values ('258', 'Reichel Inc', 'Age-rel osteopor w crnt path fx, r hand, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('259', 'Renner, Rosenbaum and Kunze', 'Collapsed vertebra, NEC, lumbar region, init');
insert into zonas_zona (id, nombre, descripcion) values ('260', 'Schmitt, Goldner and Rau', 'Fall from ice-skates');
insert into zonas_zona (id, nombre, descripcion) values ('261', 'Torphy Group', 'Other secondary chronic gout, unspecified knee, with tophus');
insert into zonas_zona (id, nombre, descripcion) values ('262', 'Harvey LLC', 'Chronic kidney disease, stage 1');
insert into zonas_zona (id, nombre, descripcion) values ('263', 'Davis-Price', 'Stress fracture, pelvis, subs for fx w routn heal');
insert into zonas_zona (id, nombre, descripcion) values ('264', 'Lemke Inc', 'Disp fx of epiphy (separation) (upper) of unsp femr, 7thN');
insert into zonas_zona (id, nombre, descripcion) values ('265', 'Sipes, Quitzon and Kutch', 'Disp fx of shaft of third MC bone, r hand, init for opn fx');
insert into zonas_zona (id, nombre, descripcion) values ('266', 'Rolfson, Paucek and Hills', 'Fall from, out of or through window, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('267', 'Schumm and Sons', 'Military operations involving incendiary bullet');
insert into zonas_zona (id, nombre, descripcion) values ('268', 'Schowalter and Sons', 'Newborn affected by multiple pregnancy');
insert into zonas_zona (id, nombre, descripcion) values ('269', 'Satterfield, Bogan and Collins', 'Poisoning by, adverse effect of and underdosing of laxatives');
insert into zonas_zona (id, nombre, descripcion) values ('270', 'Koss, Lind and Conn', 'Nondisplaced fracture of base of unspecified metacarpal bone');
insert into zonas_zona (id, nombre, descripcion) values ('271', 'Cronin and Sons', 'Complicated headache syndromes');
insert into zonas_zona (id, nombre, descripcion) values ('272', 'Bartell-Gerhold', 'Other osteomyelitis, thigh');
insert into zonas_zona (id, nombre, descripcion) values ('273', 'Williamson Inc', 'Advrs effect of antiparkns drug/centr musc-tone depr, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('274', 'Muller, Mertz and West', 'Fuchs'' heterochromic cyclitis, left eye');
insert into zonas_zona (id, nombre, descripcion) values ('275', 'Maggio, Zemlak and Gleason', 'Injury of ulnar nerve at wrs/hnd lv of right arm, subs');
insert into zonas_zona (id, nombre, descripcion) values ('276', 'Auer LLC', 'Postproc hemor of unsp and adnexa following other procedure');
insert into zonas_zona (id, nombre, descripcion) values ('277', 'Goodwin, Weimann and Koelpin', 'Sicca syndrome with lung involvement');
insert into zonas_zona (id, nombre, descripcion) values ('278', 'Waters-Gleason', 'Opioid dependence with withdrawal');
insert into zonas_zona (id, nombre, descripcion) values ('279', 'Grant LLC', 'Laceration without foreign body, right thigh, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('280', 'Jacobi LLC', 'Old myocardial infarction');
insert into zonas_zona (id, nombre, descripcion) values ('281', 'Hackett-White', 'Poisoning by pyrazolone derivatives, accidental');
insert into zonas_zona (id, nombre, descripcion) values ('282', 'Jacobs-Gaylord', 'Oth paralytic syndrome following oth ntrm intcrn hemorrhage');
insert into zonas_zona (id, nombre, descripcion) values ('283', 'Fritsch, Kulas and Bernier', 'Adverse effect of histamine H2-receptor blockers, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('284', 'Borer Group', 'Cushing''s syndrome, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('285', 'Beahan, Hettinger and Goodwin', 'Extremely low birth weight newborn, 750-999 grams');
insert into zonas_zona (id, nombre, descripcion) values ('286', 'Block, Terry and Farrell', 'Driver injured in collision w oth and unsp mv in traf');
insert into zonas_zona (id, nombre, descripcion) values ('287', 'Auer LLC', 'Spinal and epidural anesth induced headache during pregnancy');
insert into zonas_zona (id, nombre, descripcion) values ('288', 'Hayes, Schmitt and Langosh', 'Legal intervention involving oth gas, suspect injured, init');
insert into zonas_zona (id, nombre, descripcion) values ('289', 'Parisian, Osinski and Anderson', 'Unsp injury of musc/fasc/tend triceps, unsp arm, init');
insert into zonas_zona (id, nombre, descripcion) values ('290', 'Schowalter Inc', 'Corros 70-79% of body surface w 40-49% third degree corros');
insert into zonas_zona (id, nombre, descripcion) values ('291', 'Huel-Conn', 'Severe atrophy of the maxilla');
insert into zonas_zona (id, nombre, descripcion) values ('292', 'Graham LLC', 'Corrosion of second degree of left upper arm, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('293', 'Towne, Stehr and Ernser', 'Toxic effect of contact w sea anemone, undetermined, subs');
insert into zonas_zona (id, nombre, descripcion) values ('294', 'Romaguera Group', 'Other rupture of muscle (nontraumatic), unspecified thigh');
insert into zonas_zona (id, nombre, descripcion) values ('295', 'Hettinger, Glover and Hoeger', 'Toxic effect of lacrimogenic gas, accidental, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('296', 'Sanford, Ryan and Considine', 'Disp fx of med malleolus of l tibia, 7thG');
insert into zonas_zona (id, nombre, descripcion) values ('297', 'Bednar Group', 'Pnctr w/o foreign body of finger w damage to nail, subs');
insert into zonas_zona (id, nombre, descripcion) values ('298', 'Hintz Inc', 'Lacerat unsp blood vessel at hip and thigh level, left leg');
insert into zonas_zona (id, nombre, descripcion) values ('299', 'Beier, Skiles and Raynor', 'Mech compl of unspecified cardiac device, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('300', 'Hyatt, Feest and Heathcote', 'Pnctr w fb of unsp front wall of thorax w/o penet thor cav');
insert into zonas_zona (id, nombre, descripcion) values ('301', 'Weimann, Leannon and Green', 'Corros third deg of unsp site unsp low limb, ex ank/ft, subs');
insert into zonas_zona (id, nombre, descripcion) values ('302', 'Prohaska LLC', 'Palindromic rheumatism, left hip');
insert into zonas_zona (id, nombre, descripcion) values ('303', 'Gibson and Sons', 'Toxic eff of nitrodrv/aminodrv of benzn/homolog, asslt, init');
insert into zonas_zona (id, nombre, descripcion) values ('304', 'Keebler-Crooks', 'Encntr for routine child health exam w/o abnormal findings');
insert into zonas_zona (id, nombre, descripcion) values ('305', 'Schuppe, Cronin and Schuster', 'Greenstick fx shaft of unsp ulna, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('306', 'Huels Group', 'Nondisp fx of right tibial spine, init for opn fx type I/2');
insert into zonas_zona (id, nombre, descripcion) values ('307', 'Bruen-Feil', 'Interstitial myositis, multiple sites');
insert into zonas_zona (id, nombre, descripcion) values ('308', 'Stanton, Dibbert and Weissnat', 'Athscl type of bypass of the extrm w intrmt claud, left leg');
insert into zonas_zona (id, nombre, descripcion) values ('309', 'Hane, Schoen and Kshlerin', 'Other intervertebral disc degeneration, lumbar region');
insert into zonas_zona (id, nombre, descripcion) values ('310', 'Feil-Block', 'Keratopathy (bullous aphakic) fol cataract surgery, left eye');
insert into zonas_zona (id, nombre, descripcion) values ('311', 'Osinski-Connelly', 'Spinal enthesopathy, thoracolumbar region');
insert into zonas_zona (id, nombre, descripcion) values ('312', 'Lemke Group', 'Strain unsp musc/fasc/tend at forarm lv, right arm, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('313', 'Russel and Sons', 'Toxic effect of unsp metal, accidental (unintentional)');
insert into zonas_zona (id, nombre, descripcion) values ('314', 'Bednar Inc', 'Contusion of descending [left] colon, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('315', 'Gutkowski, Bogisich and Brekke', 'Labor and delivery complicated by vasa previa, fetus 2');
insert into zonas_zona (id, nombre, descripcion) values ('316', 'Franecki and Sons', 'Corrosion of unsp degree of back of right hand, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('317', 'Anderson-Bernier', 'Underdosing of peripheral vasodilators, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('318', 'Lindgren, Cummings and Mayert', 'Striking against other stationary object');
insert into zonas_zona (id, nombre, descripcion) values ('319', 'Purdy Group', 'Other disorders of iron metabolism');
insert into zonas_zona (id, nombre, descripcion) values ('320', 'Huels Inc', 'Disorder of ligament, unspecified hand');
insert into zonas_zona (id, nombre, descripcion) values ('321', 'Becker-O''Kon', 'Injury of oth nerves at lower leg level, right leg, subs');
insert into zonas_zona (id, nombre, descripcion) values ('322', 'Emmerich and Sons', 'Interstitial myositis, unspecified upper arm');
insert into zonas_zona (id, nombre, descripcion) values ('323', 'Gleason and Sons', 'Toxic effect of carb monx from mtr veh exhaust, acc, init');
insert into zonas_zona (id, nombre, descripcion) values ('324', 'Jones, Jacobson and Ritchie', 'Nondisplaced avulsion fracture of right ilium, init');
insert into zonas_zona (id, nombre, descripcion) values ('325', 'Gulgowski, Bahringer and Leuschke', 'Toxic effect of venom of oth arthropod, undetermined, init');
insert into zonas_zona (id, nombre, descripcion) values ('326', 'Beahan-Pfeffer', 'Contact w unsp hot objects, undetermined intent, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('327', 'Conn-Ritchie', 'Juvenile arthritis, unspecified, left hand');
insert into zonas_zona (id, nombre, descripcion) values ('328', 'Murazik-Schneider', 'Driver of amblnc/fire eng injured nontraf, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('329', 'Considine, Littel and Witting', 'Acute lymphangitis of trunk, unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('330', 'Kuhlman Group', 'Rheumatoid myopathy with rheumatoid arthritis of unsp wrist');
insert into zonas_zona (id, nombre, descripcion) values ('331', 'Hayes Group', 'Toxic effect of contact w oth jellyfish, self-harm, init');
insert into zonas_zona (id, nombre, descripcion) values ('332', 'Labadie and Sons', 'Unsp hormone antagonists');
insert into zonas_zona (id, nombre, descripcion) values ('333', 'Sauer-Orn', 'Osteonecrosis due to previous trauma, right femur');
insert into zonas_zona (id, nombre, descripcion) values ('334', 'Keeling-Jacobs', 'Unsp opn wnd unsp bk wl of thorax w/o penet thor cav, init');
insert into zonas_zona (id, nombre, descripcion) values ('335', 'Emmerich-Kuhlman', 'Corros first degree of unsp single finger except thumb, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('336', 'Schmitt, Gorczany and Altenwerth', 'Nondisp fx of base of 3rd MC bone, r hand, 7thK');
insert into zonas_zona (id, nombre, descripcion) values ('337', 'Batz-Gerlach', 'Underdosing of other drugs acting on muscles, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('338', 'Weber, Hauck and Luettgen', 'Insect bite (nonvenomous) of right forearm');
insert into zonas_zona (id, nombre, descripcion) values ('339', 'Labadie and Sons', 'Disp fx of proximal phalanx of right thumb, init for opn fx');
insert into zonas_zona (id, nombre, descripcion) values ('340', 'Kris, Simonis and Graham', 'Path fx in oth disease, r humerus, subs for fx w malunion');
insert into zonas_zona (id, nombre, descripcion) values ('341', 'Erdman, Zulauf and Farrell', 'Diffuse TBI w LOC >24 hr w return to conscious levels');
insert into zonas_zona (id, nombre, descripcion) values ('342', 'Kling-Wintheiser', 'Pedl cyc pasngr inj in clsn w statnry object nontraf, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('343', 'Schmeler, Hirthe and Walter', 'Unsp car occupant injured in collision w van in traf');
insert into zonas_zona (id, nombre, descripcion) values ('344', 'Smitham, Marquardt and Schowalter', 'Displaced pilon fx left tibia, subs for clos fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('345', 'Fahey, Schultz and Wiza', 'Unsp fx low end r tibia, 7thE');
insert into zonas_zona (id, nombre, descripcion) values ('346', 'Ritchie Inc', 'Torus fx upper end of l humerus, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('347', 'Ratke Group', 'Pauciarticular juvenile rheumatoid arthritis, left wrist');
insert into zonas_zona (id, nombre, descripcion) values ('348', 'Kutch, Streich and Waters', 'Contact w transmission devices, NEC, init');
insert into zonas_zona (id, nombre, descripcion) values ('349', 'Wehner Group', 'Unsp inj intrns musc/fasc/tend r little finger at wrs/hnd lv');
insert into zonas_zona (id, nombre, descripcion) values ('350', 'Williamson-Hoppe', 'Major laceration of left innominate or subclav vein, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('351', 'Gutkowski, Fisher and Fritsch', 'Horizontal alveolar bone loss');
insert into zonas_zona (id, nombre, descripcion) values ('352', 'Gottlieb-Hintz', 'Phlebitis and thrombophlebitis of lower extremities, unsp');
insert into zonas_zona (id, nombre, descripcion) values ('353', 'Miller, Stracke and Howell', 'Taeniasis');
insert into zonas_zona (id, nombre, descripcion) values ('354', 'Dooley-Wisoky', 'Transient global amnesia');
insert into zonas_zona (id, nombre, descripcion) values ('355', 'Powlowski-Russel', 'Benign neoplasm of other parts of mouth');
insert into zonas_zona (id, nombre, descripcion) values ('356', 'Stoltenberg LLC', 'Anterior cord syndrome at C2, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('357', 'Lynch, Miller and Bode', 'Central pontine myelinolysis');
insert into zonas_zona (id, nombre, descripcion) values ('358', 'Hickle, Kiehn and Bosco', 'Chronic embolism and thrombosis of left axillary vein');
insert into zonas_zona (id, nombre, descripcion) values ('359', 'Raynor-Stanton', 'Oth fx l low leg, subs for opn fx type I/2 w routn heal');
insert into zonas_zona (id, nombre, descripcion) values ('360', 'Spinka LLC', 'Quad pregnancy, unable to determine num plcnta & amnio sacs');
insert into zonas_zona (id, nombre, descripcion) values ('361', 'Weimann, Kub and Simonis', 'Fall into other water');
insert into zonas_zona (id, nombre, descripcion) values ('362', 'Collins, Marquardt and Altenwerth', 'Nondisp Rolando''s fracture, r hand, subs for fx w malunion');
insert into zonas_zona (id, nombre, descripcion) values ('363', 'Swift, Barrows and Koelpin', 'Pnctr w/o fb of abd wall, r upper q w penet perit cav, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('364', 'Mitchell Group', 'Disp fx of dist phalanx of r great toe, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('365', 'Upton-Dicki', 'Oth foreign object in esophagus causing comprsn of trachea');
insert into zonas_zona (id, nombre, descripcion) values ('366', 'Hartmann-Miller', 'Toxic effect of smoke, undetermined, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('367', 'Homenick Inc', 'Posterior sublux of proximal end of tibia, l knee, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('368', 'Stanton-Blanda', 'Unspecified effects of high altitude');
insert into zonas_zona (id, nombre, descripcion) values ('369', 'Hahn, Upton and Doyle', 'Miscellaneous physical medicine devices assoc w incdt, NEC');
insert into zonas_zona (id, nombre, descripcion) values ('370', 'Nikolaus and Sons', 'Accident to, on or involving ski lift');
insert into zonas_zona (id, nombre, descripcion) values ('371', 'Braun, Nikolaus and Hudson', 'Pedestrian injured in other and unsp transport accidents');
insert into zonas_zona (id, nombre, descripcion) values ('372', 'Hahn-Orn', 'Fall from ice-skates');
insert into zonas_zona (id, nombre, descripcion) values ('373', 'Price Group', 'Unsp mtrcy rider injured in clsn w ped/anml nontraf, init');
insert into zonas_zona (id, nombre, descripcion) values ('374', 'Crooks LLC', 'Galactorrhea');
insert into zonas_zona (id, nombre, descripcion) values ('375', 'Moen-Schuppe', 'Other blood donor, stem cells');
insert into zonas_zona (id, nombre, descripcion) values ('376', 'Predovic, Borer and Rau', 'Sltr-haris Type III physeal fx lower end of ulna, right arm');
insert into zonas_zona (id, nombre, descripcion) values ('377', 'Williamson, O''Reilly and Stiedemann', 'Wedge comprsn fx T9-T10 vertebra, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('378', 'Koepp, Kihn and Sanford', 'Nondisp seg fx shaft of l femr, 7thG');
insert into zonas_zona (id, nombre, descripcion) values ('379', 'Cartwright, Mueller and Adams', 'Glaucoma secondary to drugs, left eye, indeterminate stage');
insert into zonas_zona (id, nombre, descripcion) values ('380', 'Johns-Nienow', 'Oth fracture of unsp pubis, init encntr for closed fracture');
insert into zonas_zona (id, nombre, descripcion) values ('381', 'Rohan-Johns', 'Crushing injury of left foot');
insert into zonas_zona (id, nombre, descripcion) values ('382', 'Kautzer-Deckow', 'High school as the place of occurrence of the external cause');
insert into zonas_zona (id, nombre, descripcion) values ('383', 'Predovic, Friesen and Anderson', 'Unspecified child maltreatment, suspected, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('384', 'Hilll-Murphy', 'Contact with nonvenomous snakes');
insert into zonas_zona (id, nombre, descripcion) values ('385', 'Cronin LLC', 'Obst due to fb acc left in body fol infusn/transfusn, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('386', 'Ward, Beier and Schumm', 'External constriction of left little finger, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('387', 'Labadie-Schinner', 'Displaced comminuted fracture of shaft of unsp tibia, init');
insert into zonas_zona (id, nombre, descripcion) values ('388', 'Schuppe Group', 'Nondisp seg fx shaft of r fibula, 7thF');
insert into zonas_zona (id, nombre, descripcion) values ('389', 'Zboncak-Friesen', 'Poisoning by appetite depressants, assault, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('390', 'Kihn, McLaughlin and Roberts', 'Toxic liver disease with other disorders of liver');
insert into zonas_zona (id, nombre, descripcion) values ('391', 'Treutel Inc', 'Unsp car occ injured in clsn w nonmtr vehicle in traf, init');
insert into zonas_zona (id, nombre, descripcion) values ('392', 'Deckow-Abbott', 'Unsp superficial injuries of r bk wl of thorax, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('393', 'Rodriguez LLC', 'Oth incmpl lesion at unsp level of cerv spinal cord, init');
insert into zonas_zona (id, nombre, descripcion) values ('394', 'Waters LLC', 'Fx unsp part of scapula, l shldr, subs for fx w delay heal');
insert into zonas_zona (id, nombre, descripcion) values ('395', 'McDermott-Mitchell', 'Dislocation of left scapula, subsequent encounter');
insert into zonas_zona (id, nombre, descripcion) values ('396', 'Morissette, Greenholt and Wehner', 'Sltr-haris Type III physl fx low end ulna, r arm, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('397', 'Johns, Hamill and Ryan', 'Drug/chem diabetes with stable prolif diabetic rtnop, r eye');
insert into zonas_zona (id, nombre, descripcion) values ('398', 'Denesik-Labadie', 'Underdosing of antithyroid drugs');
insert into zonas_zona (id, nombre, descripcion) values ('399', 'Denesik-Mann', 'Displacement of implnt elec nstim, generator');
insert into zonas_zona (id, nombre, descripcion) values ('400', 'Gutkowski, Upton and Nader', 'Corros 2nd deg mul right fingers (nail), inc thumb, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('401', 'DuBuque, Gaylord and Emard', 'Personal history of malignant neoplasm of pancreas');
insert into zonas_zona (id, nombre, descripcion) values ('402', 'Steuber Group', 'Insect bite (nonvenomous) of unsp part of head, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('403', 'Hayes, Smitham and Harber', 'Adult physical abuse, suspected');
insert into zonas_zona (id, nombre, descripcion) values ('404', 'Rohan Inc', 'Contact with prime movers, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('405', 'Botsford-Schoen', 'Disp fx of lateral epicondyle of l humerus, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('406', 'Thiel-Grady', 'Nondisp fx of ant wl of unsp acetab, 7thD');
insert into zonas_zona (id, nombre, descripcion) values ('407', 'Leffler-Adams', 'Poisoning by aminoglycosides, accidental, subs');
insert into zonas_zona (id, nombre, descripcion) values ('408', 'Kuhn and Sons', 'Unspecified chorioretinal inflammation, bilateral');
insert into zonas_zona (id, nombre, descripcion) values ('409', 'Kemmer Group', 'Superficial foreign body of oth part of neck, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('410', 'Cole, Dicki and Stamm', 'Pnctr w/o foreign body of l idx fngr w/o damage to nail');
insert into zonas_zona (id, nombre, descripcion) values ('411', 'Luettgen-Franecki', 'Burn 2nd deg of unsp site unsp lower limb, ex ank/ft, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('412', 'Beahan and Sons', 'Osteitis deformans of right hand');
insert into zonas_zona (id, nombre, descripcion) values ('413', 'Lakin, Wehner and Brown', 'Dislocation of MCP joint of unsp finger, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('414', 'Strosin-Muller', 'Struck by other birds, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('415', 'Hills-Robel', 'Lateral dislocation of left patella, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('416', 'MacGyver Inc', 'Toxic effect of paints and dyes, NEC, undetermined, init');
insert into zonas_zona (id, nombre, descripcion) values ('417', 'Davis, Watsica and Nienow', 'Unsp inj blood vessels at low leg level, right leg, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('418', 'Lang, Block and Nicolas', 'Nondisp transverse fx shaft of unsp rad, 7thP');
insert into zonas_zona (id, nombre, descripcion) values ('419', 'Emmerich, Harris and Gislason', 'Inj flexor musc/fasc/tend r mid finger at forearm level');
insert into zonas_zona (id, nombre, descripcion) values ('420', 'Morissette, Kunze and Feil', 'Inflammatory polyneuropathy');
insert into zonas_zona (id, nombre, descripcion) values ('421', 'Torphy-Rolfson', 'Nondisp commnt fx shaft of humer, l arm, 7thP');
insert into zonas_zona (id, nombre, descripcion) values ('422', 'Rath Inc', 'Encounter for screening for intestinal infectious diseases');
insert into zonas_zona (id, nombre, descripcion) values ('423', 'Conroy Group', 'Toxic effect of mycotoxin food contamnt, accidental, init');
insert into zonas_zona (id, nombre, descripcion) values ('424', 'Conroy and Sons', 'Matern care for viable fetus in abd preg, third tri, fetus 5');
insert into zonas_zona (id, nombre, descripcion) values ('425', 'Koss-Emard', 'Other specified injuries of right lower leg, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('426', 'Walker Inc', 'Intentional self-harm by explosive material, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('427', 'Armstrong-Miller', 'Ben neoplm of connctv/soft tiss of right lower limb, inc hip');
insert into zonas_zona (id, nombre, descripcion) values ('428', 'Franecki, Spencer and Kihn', 'Other specified diseases of liver');
insert into zonas_zona (id, nombre, descripcion) values ('429', 'Batz and Sons', 'Crushing injury of left thumb, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('430', 'Little, Yost and Mueller', 'Burn of first degree of nose (septum), sequela');
insert into zonas_zona (id, nombre, descripcion) values ('431', 'Monahan-Kiehn', 'Enctr srvlnc implantable subdermal contraceptive');
insert into zonas_zona (id, nombre, descripcion) values ('432', 'Kemmer-Swaniawski', 'Injury of unspecified blood vessel of thorax');
insert into zonas_zona (id, nombre, descripcion) values ('433', 'Gottlieb, Nolan and Rempel', 'Nondisp fx of mid 3rd of navic bone of l wrs, 7thK');
insert into zonas_zona (id, nombre, descripcion) values ('434', 'Gerhold, Durgan and Padberg', 'Disp fx of neck of fourth MC bone, l hand, init for opn fx');
insert into zonas_zona (id, nombre, descripcion) values ('435', 'Waelchi-Kertzmann', 'Toxic effect of other alcohols');
insert into zonas_zona (id, nombre, descripcion) values ('436', 'Donnelly, Lang and Cronin', 'Perst migraine aura w cerebral infrc, not ntrct, w stat migr');
insert into zonas_zona (id, nombre, descripcion) values ('437', 'Daugherty, Kris and Price', 'Acute gastritis with bleeding');
insert into zonas_zona (id, nombre, descripcion) values ('438', 'Renner Inc', 'Toxic effect of contact w venomous marine plant, undet, subs');
insert into zonas_zona (id, nombre, descripcion) values ('439', 'Gusikowski, Hintz and Kirlin', 'Renal agenesis, bilateral');
insert into zonas_zona (id, nombre, descripcion) values ('440', 'Dicki-Christiansen', 'Nondisplaced fracture of trapezoid, right wrist, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('441', 'Blick and Sons', 'Atrial premature depolarization');
insert into zonas_zona (id, nombre, descripcion) values ('442', 'Jerde-Russel', 'Loose body in knee, right knee');
insert into zonas_zona (id, nombre, descripcion) values ('443', 'Fadel-Runolfsdottir', 'Congen absence of thigh and lower leg w foot present, bi');
insert into zonas_zona (id, nombre, descripcion) values ('444', 'Effertz-Weimann', 'Drug-induced chronic gout, left shoulder, with tophus');
insert into zonas_zona (id, nombre, descripcion) values ('445', 'Nikolaus Group', 'Unspecified fracture of right ischium, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('446', 'Miller, Bechtelar and Kemmer', 'Injury of optic tract and pathways, unsp eye, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('447', 'Spinka-Brown', 'Oth injury of unsp blood vessel at forearm level, unsp arm');
insert into zonas_zona (id, nombre, descripcion) values ('448', 'Wehner-Grant', 'Laceration of blood vessels at shldr/up arm, unsp arm, subs');
insert into zonas_zona (id, nombre, descripcion) values ('449', 'Hettinger Inc', 'Laceration with foreign body of left ear');
insert into zonas_zona (id, nombre, descripcion) values ('450', 'Thiel-Lemke', 'Traum subdr hem w LOC >24 hr w ret consc lev, init');
insert into zonas_zona (id, nombre, descripcion) values ('451', 'Hettinger, Nitzsche and Satterfield', 'Assault by steam or hot vapors, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('452', 'Wunsch-Green', 'Nexdtve age-related mclr degn, left eye, stage unspecified');
insert into zonas_zona (id, nombre, descripcion) values ('453', 'McCullough Group', 'Congenital absence of both forearm and hand');
insert into zonas_zona (id, nombre, descripcion) values ('454', 'Bartell, Lowe and Klocko', 'Occ of rail trn/veh inj d/t explosn or fire on train, init');
insert into zonas_zona (id, nombre, descripcion) values ('455', 'Sipes-Gutmann', 'Unspecified corneal degeneration');
insert into zonas_zona (id, nombre, descripcion) values ('456', 'Kutch, Luettgen and Bruen', 'Car driver injured in collision w van in traf, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('457', 'McClure, Strosin and Parker', 'Burn of third degree of left thigh');
insert into zonas_zona (id, nombre, descripcion) values ('458', 'Medhurst, Rogahn and Dickinson', 'Nondisp fx of base of 5th MC bone, r hand, 7thK');
insert into zonas_zona (id, nombre, descripcion) values ('459', 'Ratke Inc', 'Moderate laceration of heart w hemopericardium, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('460', 'Bayer-Rippin', 'Congenital hypertonia');
insert into zonas_zona (id, nombre, descripcion) values ('461', 'Bogisich LLC', 'Other respiratory disorders');
insert into zonas_zona (id, nombre, descripcion) values ('462', 'Fadel-Blick', 'Nondisp oblique fx shaft of l tibia, 7thK');
insert into zonas_zona (id, nombre, descripcion) values ('463', 'Terry, Hoeger and Erdman', 'Other fracture of occiput, left side, init');
insert into zonas_zona (id, nombre, descripcion) values ('464', 'Denesik-Kuhn', 'Adverse effect of butyrophen/thiothixen neuroleptc, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('465', 'Johns-Schoen', 'Blister (nonthermal), unspecified ankle, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('466', 'Feil Group', 'Neoplasm of uncrt behavior of the sublingual salivary gland');
insert into zonas_zona (id, nombre, descripcion) values ('467', 'Schmidt-Smitham', 'Toxic effect of formaldehyde');
insert into zonas_zona (id, nombre, descripcion) values ('468', 'Huels Inc', 'Poisoning by thyroid hormones and substitutes, undet, init');
insert into zonas_zona (id, nombre, descripcion) values ('469', 'Spencer, Turcotte and Morissette', 'Animal-rider injured in collision w rail trn/veh, init');
insert into zonas_zona (id, nombre, descripcion) values ('470', 'Hamill-Orn', 'Fracture of unspecified part of right clavicle');
insert into zonas_zona (id, nombre, descripcion) values ('471', 'Bogisich-Windler', 'Nondisp avulsion fx unsp ischium, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('472', 'Hansen Inc', 'Disp fx of nk of unsp rad, 7thR');
insert into zonas_zona (id, nombre, descripcion) values ('473', 'Von-Casper', 'Superficial frostbite of left finger(s), initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('474', 'Hartmann, Watsica and Gutkowski', 'Corrosion of third degree of unspecified elbow, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('475', 'Blanda, Daniel and Weissnat', 'Stable burst fracture of fourth lumbar vertebra, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('476', 'Smitham, Ferry and Bashirian', 'Disp fx of base of 4th MC bone, l hand, 7thK');
insert into zonas_zona (id, nombre, descripcion) values ('477', 'Kuhic-Swift', 'Burn of first degree of unspecified palm, subs encntr');
insert into zonas_zona (id, nombre, descripcion) values ('478', 'Goldner-O''Kon', 'Water transport accident involving military watercraft');
insert into zonas_zona (id, nombre, descripcion) values ('479', 'Waters Inc', 'Crushing injury of left forearm');
insert into zonas_zona (id, nombre, descripcion) values ('480', 'Rohan-Lynch', 'Encntr for mental health serv for victim or perp of abuse');
insert into zonas_zona (id, nombre, descripcion) values ('481', 'Okuneva LLC', 'Disp fx of greater trochanter of right femur, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('482', 'Treutel Inc', 'Other chorioretinal inflammations, right eye');
insert into zonas_zona (id, nombre, descripcion) values ('483', 'Purdy, Mraz and Durgan', 'Oth nondisp fx of sixth cervcal vert, subs for fx w nonunion');
insert into zonas_zona (id, nombre, descripcion) values ('484', 'Rath-Kassulke', 'Other synovitis and tenosynovitis, other site');
insert into zonas_zona (id, nombre, descripcion) values ('485', 'Fahey, Paucek and Weber', 'Burn unsp deg mult sites of right low limb, ex ank/ft, init');
insert into zonas_zona (id, nombre, descripcion) values ('486', 'Satterfield-Rosenbaum', 'Poisn by unsp nonopi analgs/antipyr/antirheu, slf-hrm, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('487', 'Lynch-Christiansen', 'Traum rupture of palmar ligmt of l mid finger at MCP/IP jt');
insert into zonas_zona (id, nombre, descripcion) values ('488', 'Gleichner, Conroy and Bergnaum', 'Partial traumatic amputation of right great toe, init encntr');
insert into zonas_zona (id, nombre, descripcion) values ('489', 'Blick, Keeling and Kemmer', 'Unsp inj unsp blood vess at ank/ft level, right leg, init');
insert into zonas_zona (id, nombre, descripcion) values ('490', 'Reichel-Gutmann', 'Newborn affected by other maternal comp of pregnancy');
insert into zonas_zona (id, nombre, descripcion) values ('491', 'Carter Inc', 'Toxic effect of venom of African and Asian snake, acc, subs');
insert into zonas_zona (id, nombre, descripcion) values ('492', 'Rohan and Sons', 'Unspecified pneumoconiosis');
insert into zonas_zona (id, nombre, descripcion) values ('493', 'Walker, Stanton and Quigley', 'Fatigue fracture of vertebra, cervical region, sqla');
insert into zonas_zona (id, nombre, descripcion) values ('494', 'Cruickshank-Boyer', 'Oth injury due to other accident to other powered watercraft');
insert into zonas_zona (id, nombre, descripcion) values ('495', 'Hilll-Paucek', 'Poisoning by antitussives, intentional self-harm, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('496', 'Jones, McCullough and Schmidt', 'Exposure to other natural radiation, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('497', 'Willms-Treutel', 'Matern care for damage to fetus from viral disease in mother');
insert into zonas_zona (id, nombre, descripcion) values ('498', 'Heidenreich Group', 'Burn of unspecified degree of left palm, initial encounter');
insert into zonas_zona (id, nombre, descripcion) values ('499', 'Kunde, Sauer and Hackett', 'Poisoning by glucocort/synth analog, assault, sequela');
insert into zonas_zona (id, nombre, descripcion) values ('500', 'Wunsch and Sons', 'Fall on board other unpowered watercraft, initial encounter');
