# Generated by Django 2.2 on 2020-03-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tienda_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=40),
        ),
    ]
